"""Diagnostics."""

from jominipy.diagnostics.codes import (
    LEXER_UNTERMINATED_STRING,
    LINT_SEMANTIC_INCONSISTENT_SHAPE,
    LINT_SEMANTIC_INVALID_FIELD_TYPE,
    LINT_SEMANTIC_MISSING_REQUIRED_FIELD,
    LINT_STYLE_SINGLE_LINE_BLOCK,
    PARSER_EXPECTED_TOKEN,
    PARSER_EXPECTED_VALUE,
    PARSER_LEGACY_EXTRA_RBRACE,
    PARSER_LEGACY_MISSING_RBRACE,
    PARSER_UNEXPECTED_TOKEN,
    PARSER_UNSUPPORTED_PARAMETER_SYNTAX,
    PARSER_UNSUPPORTED_UNMARKED_LIST,
    TYPECHECK_INCONSISTENT_VALUE_SHAPE,
    TYPECHECK_INVALID_FIELD_REFERENCE,
    TYPECHECK_INVALID_FIELD_TYPE,
    TYPECHECK_INVALID_SCOPE_CONTEXT,
    DiagnosticSpec,
)
from jominipy.diagnostics.diagnostic import Diagnostic, Severity
from jominipy.diagnostics.report import collect_diagnostics, has_errors

__all__ = [
    "LEXER_UNTERMINATED_STRING",
    "LINT_SEMANTIC_INCONSISTENT_SHAPE",
    "LINT_SEMANTIC_INVALID_FIELD_TYPE",
    "LINT_SEMANTIC_MISSING_REQUIRED_FIELD",
    "LINT_STYLE_SINGLE_LINE_BLOCK",
    "PARSER_EXPECTED_TOKEN",
    "PARSER_EXPECTED_VALUE",
    "PARSER_LEGACY_EXTRA_RBRACE",
    "PARSER_LEGACY_MISSING_RBRACE",
    "PARSER_UNEXPECTED_TOKEN",
    "PARSER_UNSUPPORTED_PARAMETER_SYNTAX",
    "PARSER_UNSUPPORTED_UNMARKED_LIST",
    "TYPECHECK_INCONSISTENT_VALUE_SHAPE",
    "TYPECHECK_INVALID_FIELD_REFERENCE",
    "TYPECHECK_INVALID_FIELD_TYPE",
    "TYPECHECK_INVALID_SCOPE_CONTEXT",
    "Diagnostic",
    "DiagnosticSpec",
    "Severity",
    "collect_diagnostics",
    "has_errors",
]
