"""CWTools-like rules ingest and normalized IR utilities."""

from jominipy.rules.adapter import (
    ExpandedFieldConstraints,
    SubtypeMatcher,
    build_alias_members_by_family,
    build_expanded_field_constraints,
    build_subtype_field_constraints_by_object,
    build_subtype_matchers_by_object,
    load_hoi4_alias_members_by_family,
    load_hoi4_expanded_field_constraints,
    load_hoi4_subtype_field_constraints_by_object,
    load_hoi4_subtype_matchers_by_object,
)
from jominipy.rules.ir import (
    IndexedRuleStatement,
    RuleCardinality,
    RuleExpression,
    RuleFileIR,
    RuleMetadata,
    RuleOption,
    RuleScopeReplacement,
    RuleSetIR,
    RuleStatement,
)
from jominipy.rules.load import (
    LoadRulesResult,
    load_rules_directory,
    load_rules_paths,
)
from jominipy.rules.parser import parse_rules_file, parse_rules_text, to_file_ir
from jominipy.rules.result import RulesParseResult
from jominipy.rules.schema_graph import (
    RuleSchemaGraph,
    build_schema_graph,
    load_hoi4_schema_graph,
)
from jominipy.rules.semantics import (
    RuleFieldConstraint,
    RuleFieldScopeConstraint,
    RuleValueSpec,
    build_field_constraints_by_object,
    build_field_scope_constraints_by_object,
    build_required_fields_by_object,
    load_hoi4_enum_values,
    load_hoi4_field_constraints,
    load_hoi4_field_scope_constraints,
    load_hoi4_known_scopes,
    load_hoi4_required_fields,
    load_hoi4_type_keys,
)
from jominipy.rules.type_members import (
    TypeDefinition,
    build_type_memberships_from_file_texts,
    collect_file_texts_under_root,
    extract_type_definitions,
)

__all__ = [
    "ExpandedFieldConstraints",
    "IndexedRuleStatement",
    "LoadRulesResult",
    "RuleCardinality",
    "RuleExpression",
    "RuleFieldConstraint",
    "RuleFieldScopeConstraint",
    "RuleFileIR",
    "RuleMetadata",
    "RuleOption",
    "RuleSchemaGraph",
    "RuleScopeReplacement",
    "RuleSetIR",
    "RuleStatement",
    "RuleValueSpec",
    "RulesParseResult",
    "SubtypeMatcher",
    "TypeDefinition",
    "build_alias_members_by_family",
    "build_expanded_field_constraints",
    "build_field_constraints_by_object",
    "build_field_scope_constraints_by_object",
    "build_required_fields_by_object",
    "build_schema_graph",
    "build_subtype_field_constraints_by_object",
    "build_subtype_matchers_by_object",
    "build_type_memberships_from_file_texts",
    "collect_file_texts_under_root",
    "extract_type_definitions",
    "load_hoi4_alias_members_by_family",
    "load_hoi4_enum_values",
    "load_hoi4_expanded_field_constraints",
    "load_hoi4_field_constraints",
    "load_hoi4_field_scope_constraints",
    "load_hoi4_known_scopes",
    "load_hoi4_required_fields",
    "load_hoi4_schema_graph",
    "load_hoi4_subtype_field_constraints_by_object",
    "load_hoi4_subtype_matchers_by_object",
    "load_hoi4_type_keys",
    "load_rules_directory",
    "load_rules_paths",
    "parse_rules_file",
    "parse_rules_text",
    "to_file_ir",
]
